version: "3.9"

services:
  payment-service:
    build: payment-service/
    links:
      - payment-db

  payment-db:
    image: postgres:14.1-alpine
    container_name: payment-db
    ports:
      - "5532:5432"
    volumes:
      - ./.docker/database/init/payment:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payment-db

  study-center:
    build: study-center/
    ports:
      - "8190:8190"
    links:
      - study-db
      - payment-service

  study-db:
    image: postgres:14.1-alpine
    container_name: study-db
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/database/init/study:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=study-db